[tool.poetry]
name = "pyeutl"
version = "0.1.0"
description = "Methods to access data of the EUTL"
authors = ["jabrel"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "3.8.1"
pandas = "1.3.5"
psycopg2 = "2.9.3"
sqlalchemy = "1.4.29"
openpyxl = "^3.1.2"
ipykernel = "^6.26.0"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
